### ISSUE TITLE
Error when Exporting Release Build with AIR 3.8

### ISSUE THREAD

**Issue by bjeld** [nweber/SystemVolumeNativeExtension#4]
See Attached Image:
![error](https://f.cloud.github.com/assets/343736/1049343/b1d1f31e-10a2-11e3-8dd4-0929110673bc.png)

**Comment by bjeld** [comment]
I guess its related to this:
...when compiling and packaging apps for iOS against AIR 3.8, if the app uses a native extensions, it might cause the following error:"

internal_package-ios:
     [exec] ld: -pie can only be used when targeting iOS 4.2 or later
     [exec] Compilation failed while executing : ld64

**Comment by CoIin** [comment]
This problem happens with AIR 13.0.0.64, which builds for iOS 7 I believe. Here is the error:

Invalid input. ld: -pie can only be used when targeting iOS 4.2 or later
